### PR TITLE
added BirthdayParadox.pdf

### PR DESCRIPTION
**Pull request by mqrek**
# CHANGES

- added BirthdayParadox.pdf
- removed History and Latex brackets in BirthdayUI.R
- added iframe element to represent BirthdayParadox.pdf

# TESTING
- tested manually, if everything still works fine

# FOR REVIEWER
To identify errors, I recommend carefully reviewing the text 😄. 
Since this might be my final update (assuming no errors are found), feel free to explore and test to help identify any potential issues. Thank you!

### CODE REVIEW

**Review by SebastianUniTue — APPROVED** [review]
Thank you for your code,
I tried for different values and everything seemed fine. I also like your text. Some things I would write differently, but this is a matter of preference of style. 
One thing that could be improved in my opinion is: `5.3. Probability share same birthday as you:` but it's not a really a problem

**Comment by mqrek** [comment]
> Thank you for your code,
> I tried for different values and everything seemed fine. I also like your text. Some things I would write differently, but this is a matter of preference of style.
> One thing that could be improved in my opinion is: `5.3. Probability share same birthday as you:` but it's not a really a problem

Thanks for that hint, I will definitely change this title.

**Comment by mqrek** [comment]
New title for 5.3.: 5.3. Probability of sharing a specific birthday with a person in a group: , do you think this title fits better ?

**Comment by SebastianUniTue** [comment]
Yeah thanks for the change

**Pull request merged**
